language: node_js
node_js: node
env:
  - UNIFIED_OPTIMIZE_IMAGES=1
deploy:
  provider: pages
  local_dir: build
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN
  email: tituswormer@gmail.com
  name: Titus Wormer
  on:
    branch: src
